### ISSUE TITLE
Use getpass to get bot token for security

### ISSUE THREAD

**Issue by DevHyperCoder** [ahnaf-zamil/heater#1]
Hello, i would like heater to use `getpass` for getting the bot token. This way, when you paste it, it doesn't show it on the screen, just like how git;s Password: prompt works.

I can make a PR using `getpass` which is in stdlib, no deps required

Thank You,
DevHyperCoder

**Comment by ahnaf-zamil** [comment]
First of all, thank you for contributing to Heater, by even making an issue!

Yes, I do get your point. It would be a great idea to implement something like that. I made and released Heater in 3 hours yesterday, so I didn't put much thought into this. If you want to make a PR for this, it would be appreciated :)

**Comment by DevHyperCoder** [comment]
I will make a PR soon :)

Thanks

**Comment by DevHyperCoder** [comment]
PR merged. Closing :)
